### ISSUE TITLE
Output compiled queries at buildtime

### ISSUE THREAD

**Issue by reginsmol** [zalando-incubator/graphql-jit#178]
Is it possible to compile queries and have the function output in some way?

The rationale is that I don't want to wait for queries to come in to build up the cache of compiled queries at runtime. This isn't ideal when the GraphQL API is running in a cluster environment, as there's no guarantee the containers will have any or all compiled versions of the query.

**Comment by boopathi** [comment]
GraphQL-JIT actually exposes the function output when a debug flag is set in options. The only use-case we have is for the REPL(https://try-graphql-jit.boopathi.in/) and inspections. I don't think this would be useful in a production system - because the function is not the only output of compilation. The function depends on other objects (ExecutionContext) to run - https://github.com/zalando-incubator/graphql-jit/blob/03249741edb79d431b24645cf8346d4fee995a92/src/execution.ts#L352-L371

**Comment by reginsmol** [comment]
I appreciate you getting back to me. I messed around seeing if it was possible to hack something together (it was unsuccessful, lol) 

Do you think there's any potential for being able to compile queries at build time in a future version? Or is it just not feasible? Regardless I very much appreciate your help 🙏

**Comment by boopathi** [comment]
Right now there is no plan to make the compilation output serialize-and-restore capable.

You can also try something with the new NodeJS capabilities of using v8 snapshots - [build-snapshot](https://nodejs.org/dist/latest-v18.x/docs/api/cli.html#--build-snapshot), [release notes](https://nodejs.org/en/blog/release/v18.8.0/) . Using snapshots, you can compile the queries at build time, save it to a snapshot, and restore the application state from this snapshot file while starting the server.
